services:
  khdev:
    build:
      context: .
      dockerfile: Dockerfile
    image: khdev
    volumes:
      - ./:/app
      - ${LOCAL_DATA_PATH}:/app/data
    container_name: khdev
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "3000:3000"
